- hosts: mesh
  tasks:
  - name: install wireguard repository (debian/ubuntu)
    apt_repository: 
      repo: ppa:wireguard/wireguard
      state: present
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: install wireguard
    apt: 
      pkg: 
      - wireguard-tools
      - wireguard-dkms
      state: latest

  - name: generate private_key
    shell: wg genkey
    register: WG_KEY

  - name: generate pub_key
    shell: echo {{ WG_KEY.stdout_lines[0] }} | wg pubkey
    register: WG_PUB
    when: WG_KEY 

  - name: get ip address
    shell: dig +short myip.opendns.com @resolver1.opendns.com
    register: PUBLIC_IP

  - name: create configfile from template
    template: 
      src: mesh.1.conf.j2
      dest: /etc/wireguard/mesh.1.conf
      mode: 0644
      force: yes

  - name: create pubfile
    copy:
      dest: "/etc/wireguard/publickey"
      content: >
        {{ WG_PUB.stdout_lines[0] }}

  - name: start wireguard
    systemd:
      name:  wg-quick@mesh.1
      state: restarted
      enabled: yes
    tags:
      - restart
